2025-02-26 23:32:13,603 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2025-02-26 23:32:13,607 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application_default']
2025-02-26 23:32:13,647 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application-default', 'login']
2025-02-26 23:32:13,651 DEBUG    root            Running [gcloud.auth.application-default.login] with arguments: []
2025-02-26 23:32:22,489 DEBUG    root            (gcloud.auth.application-default.login) Aborted by user.
Traceback (most recent call last):
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 934, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/../lib/google-cloud-sdk/lib/surface/auth/application_default/login.py", line 147, in Run
    console_io.PromptContinue(
  File "/usr/bin/../lib/google-cloud-sdk/lib/googlecloudsdk/core/console/console_io.py", line 305, in PromptContinue
    raise OperationCancelledError(cancel_string)
googlecloudsdk.core.console.console_io.OperationCancelledError: Aborted by user.
2025-02-26 23:32:22,500 ERROR    root            (gcloud.auth.application-default.login) Aborted by user.
